plugin_id = "clockwork-benchmarks"
display_name = "Clockwork Loader Benchmarks"
version = "0.5"
authors = ["m00nl1ght"]
processors = ["extension.annotations.eventhandler"]
main_class = "dev.m00nl1ght.clockwork.benchmarks.ClockworkBenchmarks"
description = '''
Contains some benchmarks for Clockwork Loader
'''

[[dependency]]
id = "cwl-annotations"

[[target]]
id = "test-target"
class = "dev.m00nl1ght.clockwork.benchmarks.TestTarget"

[[component]]
id = "test-component"
class = "dev.m00nl1ght.clockwork.benchmarks.TestComponent"
target = "clockwork-benchmarks:test-target"
