plugin_id = "test-env"
display_name = "Test Environment"
version = "0.5"
authors = ["m00nl1ght"]
main_class = "dev.m00nl1ght.clockwork.test.TestEnvPlugin"
description = '''
Test environment for CWL dev workspace
'''

[[dependency]]
id = "cwl-eventhandler-annotation"

[[target]]
id = "test-target-a"
class = "dev.m00nl1ght.clockwork.test.TestTarget_A"

[[target]]
id = "test-target-b"
parent = "test-target-a"
class = "dev.m00nl1ght.clockwork.test.TestTarget_B"

[[target]]
id = "test-target-c"
class = "dev.m00nl1ght.clockwork.test.TestTarget_C"
