plugin_id = "clockwork"
display_name = "Clockwork Plugin Loader"
version = "0.5"
authors = ["m00nl1ght"]
main_class = "dev.m00nl1ght.clockwork.core.CWLPlugin"
description = '''
Universal plugin framework for Java
'''

[[target]]
id = "core"
class = "dev.m00nl1ght.clockwork.core.ClockworkCore"
