plugin_id = "test-plugin-a"
display_name = "Test Plugin A"
version = "0.5"
authors = ["m00nl1ght"]
processors = ["extension.annotations.eventhandler"]
main_class = "dev.m00nl1ght.clockwork.test.plugin.a.TestPlugin_A"
description = '''
Test Plugin for Dev environment
'''

[[dependency]]
id = "test-env"

[[dependency]]
id = "cwl-annotations"


[[component]]
id = "test-component-a"
target = "test-env:test-target-a"
class = "dev.m00nl1ght.clockwork.test.plugin.a.TestComponent_A"

[[component]]
id = "test-component-b"
target = "test-env:test-target-b"
class = "dev.m00nl1ght.clockwork.test.plugin.a.TestComponent_B"

[[component]]
id = "test-component-c"
target = "test-env:test-target-c"
class = "dev.m00nl1ght.clockwork.test.plugin.a.TestComponent_C"
