plugin_id = "test-plugin-a"
display_name = "Test Plugin A"
version = "0.5"
authors = ["m00nl1ght"]
processors = ["extension.annotations.eventhandler"]
main_class = "dev.m00nl1ght.clockwork.test.plugin.a.TestPlugin_A"
description = '''
Test Plugin for Dev environment
'''

[[dependency]]
id = "test-env"

[[dependency]]
id = "cwl-annotations"
