plugin_id = "cwl-eventhandler-annotation"
display_name = "[CWL-Extension] EventHandler Annotation"
version = "0.5"
authors = ["m00nl1ght"]
main_class = "dev.m00nl1ght.clockwork.extension.eventhandler.CWLEventHandlerExtension"
description = '''
An extension for the Clockwork Loader that provides support for @EventHandler annotations.
'''

[[dependency]]
id = "clockwork"
version = "0.5"
