plugin_id = "test-plugin"
display_name = "Test Plugin"
version = "1.0"
authors = ["m00nl1ght"]
main_class = "dev.m00nl1ght.clockwork.test.plugin.TestPlugin"
description = '''
Test Plugin for Dev environment
'''
