plugin_id = "test-plugin"
display_name = "Test Plugin"
version = "0.5"
authors = ["m00nl1ght"]
main_class = "TestPlugin"
description = '''
Test Plugin for Dev environment
'''

[[dependency]]
id = "test-env"

[[dependency]]
id = "cwl-annotations"

[[component]]
id = "test-component-a"
class = "TestComponent_A"
target = "test-env:test-target-a"

[[component]]
id = "test-component-b"
class = "TestComponent_B"
target = "test-env:test-target-b"
