plugin_id = "cwl-jar-in-jar"
display_name = "[CWL-Extension] Jar-in-Jar support"
version = "0.5"
authors = ["m00nl1ght"]
main_class = "dev.m00nl1ght.clockwork.extension.jarinjar.CWLJarInJarExtension"
description = '''
An extension for the Clockwork Loader that supports loading dependencies from within plugin jars.
'''

[[dependency]]
id = "clockwork"
version = "0.5"
